export const position = [
  { position: "0", name: "GK" },
  { position: "1", name: "SW" },
  { position: "2", name: "RWB" },
  { position: "3", name: "RB" },
  { position: "4", name: "RCB" },
  { position: "5", name: "CB" },
  { position: "6", name: "LCB" },
  { position: "7", name: "LB" },
  { position: "8", name: "LWB" },
  { position: "9", name: "RDM" },
  { position: "10", name: "CDM" },
  { position: "11", name: "LDM" },
  { position: "12", name: "RM" },
  { position: "13", name: "RCM" },
  { position: "14", name: "CM" },
  { position: "15", name: "LCM" },
  { position: "16", name: "LM" },
  { position: "17", name: "RAM" },
  { position: "18", name: "CAM" },
  { position: "19", name: "LAM" },
  { position: "20", name: "RF" },
  { position: "21", name: "CF" },
  { position: "22", name: "LF" },
  { position: "23", name: "RW" },
  { position: "24", name: "RS" },
  { position: "25", name: "ST" },
  { position: "26", name: "LS" },
  { position: "27", name: "LW" },
  { position: "28", name: "SUB" },
];

export const season = [
  { id: "101", name: "ICON (ICON)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/icon.png" },
  { id: "201", name: "NHD (National Hero Debut)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/nhd.png" },
  { id: "202", name: "TKI (Team Korea Icon)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/tki.png" },
  { id: "206", name: "TB (Tournament Best)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/tb.png" },
  { id: "207", name: "TT (Top Transfer)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/tt.png" },
  { id: "210", name: "GR (Golden Rookies)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/gr.png" },
  { id: "211", name: "19 TOTY (19 Team Of The Year)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/19toty.png" },
  { id: "212", name: "18 TOTY (18 Team Of The Year)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/18toty.png" },
  { id: "213", name: "Man City ICON (Man City ICON)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/mcicon.png" },
  { id: "214", name: "TC (Tournament Champions)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/tc.png" },
  {
    id: "215",
    name: "19 TOTS (19 Team Of The Season)",
    seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/19tots.png",
  },
  { id: "216", name: "HOT (Heroes Of the Team)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/hot.png" },
  { id: "217", name: "COC (Competitor Of Continents)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/coc.png" },
  { id: "218", name: "OTW (Ones To Watch)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/otw.png" },
  { id: "219", name: "19NG (19 NEW GENERATION)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/19ng.png" },
  { id: "220", name: "20 TOTY (20 Team Of The Year)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/20toty.png" },
  {
    id: "221",
    name: "19 UCL (19 UEFA Champions League)",
    seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/19ucl.png",
  },
  {
    id: "222",
    name: "20 TOTN (20 Team Of The Nominated)",
    seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/20totn.png",
  },
  { id: "225", name: "TKL (TEAM K LEAGUE)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/tkl.png" },
  {
    id: "230",
    name: "20 TOTS (20 Team Of The Season)",
    seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/20tots.png",
  },
  { id: "231", name: "VTR (Veteran)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/vtr.png" },
  { id: "233", name: "MOG (Moments Of Glory)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/mog.png" },
  { id: "234", name: "LH (Loyal Heroes)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/lh.png" },
  { id: "236", name: "LA (Liverpool Ambassador)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/la.png" },
  { id: "237", name: "MC (Multi-League Champions)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/mc.png" },
  { id: "238", name: "20NG (20 NEW GENERATION)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/20ng.png" },
  { id: "239", name: "20KLB (20 K-League Best)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/20klb.png" },
  { id: "240", name: "21 TOTY (21 Team Of The Year)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/21toty.png" },
  {
    id: "241",
    name: "21 TOTN (21 Team Of The Nominated)",
    seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/21totn.png",
  },
  {
    id: "242",
    name: "20 UCL (20 UEFA Champions League)",
    seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/20ucl.png",
  },
  { id: "246", name: "UP (Unsung Players)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/up.png" },
  { id: "247", name: "2012 KH (2012 KH)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/2012kh.png" },
  { id: "249", name: "NTG (Nostalgia)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/ngt.png" },
  {
    id: "250",
    name: "21 TOTS (21 Team Of The Season)",
    seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/21tots.png",
  },
  { id: "251", name: "EBS (European Best Stars)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/ebs.png" },
  { id: "252", name: "CAP (Captain)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/cap.png" },
  { id: "253", name: "BOE21 (Best of Europe 21)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/boe21.png" },
  { id: "254", name: "CFA (Chelsea FC Ambassador)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/cfa.png" },
  { id: "256", name: "BTB (Back to Back)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/btb.png" },
  { id: "257", name: "21KLB (21 K-League Best)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/21klb.png" },
  { id: "258", name: "22 TOTY (22 Team Of The Year)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/22toty.png" },
  {
    id: "259",
    name: "22 TOTN (22 Team Of The Nominated)",
    seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/22totn.png",
  },
  {
    id: "260",
    name: "21 UCL (21 UEFA Champions League)",
    seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/21ucl.png",
  },
  { id: "261", name: "22HR (22 Heroes)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/22hr.png" },
  { id: "262", name: "21NG (21 NEW GENERATION)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/21ng.png" },
  { id: "264", name: "FA (FREE AGENT)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/fa.png" },
  { id: "265", name: "LOL (LEGEND OF THE LOAN)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/lol.png" },
  {
    id: "267",
    name: "22 TOTS (22 Team Of The Season)",
    seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/22tots.png",
  },
  { id: "294", name: "21 KFA (21 KFA)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/21kfa.png" },
  { id: "295", name: "19 KFA (19 KFA)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/2019kfa.png" },
  { id: "297", name: "MCFC (17-18 Man City Champions)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/mcfc.png" },
  { id: "298", name: "18 KFA (18 KFA)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/kfa.png" },
  { id: "300", name: "21 LIVE (21 LIVE)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/live.png" },
  { id: "317", name: "17 LIVE (17 LIVE)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/17.png" },
  { id: "318", name: "18 LIVE (18 LIVE)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/18.png" },
  { id: "319", name: "19 LIVE (19 LIVE)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/19.png" },
  { id: "320", name: "20 LIVE (20 LIVE)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/20.png" },
  { id: "500", name: "18 PLC–A (18 Premium Live Autumn)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/plc.png" },
  {
    id: "501",
    name: "18 PLC–S (18 Premium Live Spring)",
    seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/18pls.png",
  },
  {
    id: "502",
    name: "19 PLC–A (19 Premium Live Autumn)",
    seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/19pla.png",
  },
  {
    id: "503",
    name: "19 PLC–S (19 Premium Live Spring)",
    seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/19pls.png",
  },
  { id: "504", name: "20KLeague (20KLeague)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/20kl.png" },
  { id: "506", name: "20 PL (20 Premium Live)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/20pla.png" },
  { id: "507", name: "21KLeague (21KLeague)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/21kl.png" },
  { id: "508", name: "21 PL (21 Premium Live)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/21pla.png" },
  { id: "510", name: "22KLeague (22KLeague)", seasonId: "https://ssl.nexon.com/s2/game/fo4/obt/externalAssets/season/22kl.png" },
];
